/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CanisterId = Principal;
export interface CanisterResources {
  'memory' : MemoryBreakdown,
  'burnRateCyclesPerDay' : bigint,
  'cycleBalance' : Cycles,
  'settings' : CanisterSettings,
  'runwayDays' : bigint,
}
export interface CanisterSettings {
  'freezingThreshold' : bigint,
  'memoryAllocation' : bigint,
  'computeAllocation' : bigint,
}
export type CanisterStatus = { 'stopped' : null } |
  { 'stopping' : null } |
  { 'unknown' : string } |
  { 'running' : null };
export interface CanisterStatusInfo {
  'status' : CanisterStatus,
  'controllers' : Array<string>,
  'resources' : CanisterResources,
  'canisterId' : CanisterId,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Cycles = bigint;
export interface IcpToCyclesRate {
  'icpPerXdr' : bigint,
  'updatedAt' : Timestamp,
}
export interface ManagedCanister {
  'addedAt' : Timestamp,
  'canisterId' : CanisterId,
}
export interface MemoryBreakdown {
  'stableBytes' : bigint,
  'heapBytes' : bigint,
  'wasmBytes' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Timestamp = bigint;
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  'addCanister' : ActorMethod<[string], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getActiveCanister' : ActorMethod<[], [] | [CanisterId]>,
  'getApiDoc' : ActorMethod<[], string>,
  'getBackendCanisterId' : ActorMethod<[], string>,
  'getCanisterCycleBalance' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getCanisterResources' : ActorMethod<
    [string],
    { 'ok' : CanisterResources } |
      { 'err' : string }
  >,
  'getCanisterStatus' : ActorMethod<
    [string],
    { 'ok' : CanisterStatusInfo } |
      { 'err' : string }
  >,
  'getIcpToCyclesRate' : ActorMethod<[], IcpToCyclesRate>,
  'listManagedCanisters' : ActorMethod<[], Array<ManagedCanister>>,
  'refreshIcpToCyclesRate' : ActorMethod<[], IcpToCyclesRate>,
  'removeCanister' : ActorMethod<[string], undefined>,
  'schema' : ActorMethod<[], string>,
  'setActiveCanister' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];