/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const CanisterId = IDL.Principal;
export const MemoryBreakdown = IDL.Record({
  'stableBytes' : IDL.Nat,
  'heapBytes' : IDL.Nat,
  'wasmBytes' : IDL.Nat,
});
export const Cycles = IDL.Nat;
export const CanisterSettings = IDL.Record({
  'freezingThreshold' : IDL.Nat,
  'memoryAllocation' : IDL.Nat,
  'computeAllocation' : IDL.Nat,
});
export const CanisterResources = IDL.Record({
  'memory' : MemoryBreakdown,
  'burnRateCyclesPerDay' : IDL.Nat,
  'cycleBalance' : Cycles,
  'settings' : CanisterSettings,
  'runwayDays' : IDL.Nat,
});
export const CanisterStatus = IDL.Variant({
  'stopped' : IDL.Null,
  'stopping' : IDL.Null,
  'unknown' : IDL.Text,
  'running' : IDL.Null,
});
export const CanisterStatusInfo = IDL.Record({
  'status' : CanisterStatus,
  'controllers' : IDL.Vec(IDL.Text),
  'resources' : CanisterResources,
  'canisterId' : CanisterId,
});
export const Timestamp = IDL.Int;
export const IcpToCyclesRate = IDL.Record({
  'icpPerXdr' : IDL.Nat,
  'updatedAt' : Timestamp,
});
export const ManagedCanister = IDL.Record({
  'addedAt' : Timestamp,
  'canisterId' : CanisterId,
});

export const idlService = IDL.Service({
  'addCanister' : IDL.Func([IDL.Text], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getActiveCanister' : IDL.Func([], [IDL.Opt(CanisterId)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getBackendCanisterId' : IDL.Func([], [IDL.Text], ['query']),
  'getCanisterCycleBalance' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'getCanisterResources' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : CanisterResources, 'err' : IDL.Text })],
      [],
    ),
  'getCanisterStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : CanisterStatusInfo, 'err' : IDL.Text })],
      [],
    ),
  'getIcpToCyclesRate' : IDL.Func([], [IcpToCyclesRate], ['query']),
  'listManagedCanisters' : IDL.Func([], [IDL.Vec(ManagedCanister)], ['query']),
  'refreshIcpToCyclesRate' : IDL.Func([], [IcpToCyclesRate], []),
  'removeCanister' : IDL.Func([IDL.Text], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setActiveCanister' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const CanisterId = IDL.Principal;
  const MemoryBreakdown = IDL.Record({
    'stableBytes' : IDL.Nat,
    'heapBytes' : IDL.Nat,
    'wasmBytes' : IDL.Nat,
  });
  const Cycles = IDL.Nat;
  const CanisterSettings = IDL.Record({
    'freezingThreshold' : IDL.Nat,
    'memoryAllocation' : IDL.Nat,
    'computeAllocation' : IDL.Nat,
  });
  const CanisterResources = IDL.Record({
    'memory' : MemoryBreakdown,
    'burnRateCyclesPerDay' : IDL.Nat,
    'cycleBalance' : Cycles,
    'settings' : CanisterSettings,
    'runwayDays' : IDL.Nat,
  });
  const CanisterStatus = IDL.Variant({
    'stopped' : IDL.Null,
    'stopping' : IDL.Null,
    'unknown' : IDL.Text,
    'running' : IDL.Null,
  });
  const CanisterStatusInfo = IDL.Record({
    'status' : CanisterStatus,
    'controllers' : IDL.Vec(IDL.Text),
    'resources' : CanisterResources,
    'canisterId' : CanisterId,
  });
  const Timestamp = IDL.Int;
  const IcpToCyclesRate = IDL.Record({
    'icpPerXdr' : IDL.Nat,
    'updatedAt' : Timestamp,
  });
  const ManagedCanister = IDL.Record({
    'addedAt' : Timestamp,
    'canisterId' : CanisterId,
  });
  
  return IDL.Service({
    'addCanister' : IDL.Func([IDL.Text], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getActiveCanister' : IDL.Func([], [IDL.Opt(CanisterId)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getBackendCanisterId' : IDL.Func([], [IDL.Text], ['query']),
    'getCanisterCycleBalance' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'getCanisterResources' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : CanisterResources, 'err' : IDL.Text })],
        [],
      ),
    'getCanisterStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : CanisterStatusInfo, 'err' : IDL.Text })],
        [],
      ),
    'getIcpToCyclesRate' : IDL.Func([], [IcpToCyclesRate], ['query']),
    'listManagedCanisters' : IDL.Func(
        [],
        [IDL.Vec(ManagedCanister)],
        ['query'],
      ),
    'refreshIcpToCyclesRate' : IDL.Func([], [IcpToCyclesRate], []),
    'removeCanister' : IDL.Func([IDL.Text], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setActiveCanister' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };