/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BalanceResult = { 'ok' : bigint } |
  { 'err' : string };
export interface BalanceSnapshot {
  'balance' : bigint,
  'timestamp' : Timestamp,
  'canisterId' : CanisterId,
}
export interface BurnRateInfo {
  'cyclesPerDay' : number,
  'projectedDepletionDate' : Timestamp,
  'snapshotCount' : bigint,
  'daysRemaining' : number,
}
export type CanisterId = Principal;
export interface CanisterStatusInfo {
  'status' : string,
  'controllers' : Array<Principal>,
  'balance' : bigint,
  'threshold' : bigint,
  'alertEnabled' : boolean,
  'lastChecked' : Timestamp,
  'belowThreshold' : boolean,
  'canisterId' : CanisterId,
}
export type StatusResult = { 'ok' : CanisterStatusInfo } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'connectCanister' : ActorMethod<[string], undefined>,
  'disconnectCanister' : ActorMethod<[string], undefined>,
  'getBackendCanisterId' : ActorMethod<[], string>,
  'getBalanceHistory' : ActorMethod<[string], Array<BalanceSnapshot>>,
  'getBurnRate' : ActorMethod<[string], BurnRateInfo>,
  'getCanisterCycleBalance' : ActorMethod<[string], BalanceResult>,
  'getCanisterStatus' : ActorMethod<[string], StatusResult>,
  'getMonitoredCanisters' : ActorMethod<[], Array<CanisterStatusInfo>>,
  'setAlertEnabled' : ActorMethod<[string, boolean], undefined>,
  'setThreshold' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];