/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const CanisterId = IDL.Principal;
export const BalanceSnapshot = IDL.Record({
  'balance' : IDL.Nat,
  'timestamp' : Timestamp,
  'canisterId' : CanisterId,
});
export const BurnRateInfo = IDL.Record({
  'cyclesPerDay' : IDL.Float64,
  'projectedDepletionDate' : Timestamp,
  'snapshotCount' : IDL.Nat,
  'daysRemaining' : IDL.Float64,
});
export const BalanceResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const CanisterStatusInfo = IDL.Record({
  'status' : IDL.Text,
  'controllers' : IDL.Vec(IDL.Principal),
  'balance' : IDL.Nat,
  'threshold' : IDL.Nat,
  'alertEnabled' : IDL.Bool,
  'lastChecked' : Timestamp,
  'belowThreshold' : IDL.Bool,
  'canisterId' : CanisterId,
});
export const StatusResult = IDL.Variant({
  'ok' : CanisterStatusInfo,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'connectCanister' : IDL.Func([IDL.Text], [], []),
  'disconnectCanister' : IDL.Func([IDL.Text], [], []),
  'getBackendCanisterId' : IDL.Func([], [IDL.Text], ['query']),
  'getBalanceHistory' : IDL.Func([IDL.Text], [IDL.Vec(BalanceSnapshot)], []),
  'getBurnRate' : IDL.Func([IDL.Text], [BurnRateInfo], []),
  'getCanisterCycleBalance' : IDL.Func([IDL.Text], [BalanceResult], []),
  'getCanisterStatus' : IDL.Func([IDL.Text], [StatusResult], []),
  'getMonitoredCanisters' : IDL.Func([], [IDL.Vec(CanisterStatusInfo)], []),
  'setAlertEnabled' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setThreshold' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const CanisterId = IDL.Principal;
  const BalanceSnapshot = IDL.Record({
    'balance' : IDL.Nat,
    'timestamp' : Timestamp,
    'canisterId' : CanisterId,
  });
  const BurnRateInfo = IDL.Record({
    'cyclesPerDay' : IDL.Float64,
    'projectedDepletionDate' : Timestamp,
    'snapshotCount' : IDL.Nat,
    'daysRemaining' : IDL.Float64,
  });
  const BalanceResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const CanisterStatusInfo = IDL.Record({
    'status' : IDL.Text,
    'controllers' : IDL.Vec(IDL.Principal),
    'balance' : IDL.Nat,
    'threshold' : IDL.Nat,
    'alertEnabled' : IDL.Bool,
    'lastChecked' : Timestamp,
    'belowThreshold' : IDL.Bool,
    'canisterId' : CanisterId,
  });
  const StatusResult = IDL.Variant({
    'ok' : CanisterStatusInfo,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'connectCanister' : IDL.Func([IDL.Text], [], []),
    'disconnectCanister' : IDL.Func([IDL.Text], [], []),
    'getBackendCanisterId' : IDL.Func([], [IDL.Text], ['query']),
    'getBalanceHistory' : IDL.Func([IDL.Text], [IDL.Vec(BalanceSnapshot)], []),
    'getBurnRate' : IDL.Func([IDL.Text], [BurnRateInfo], []),
    'getCanisterCycleBalance' : IDL.Func([IDL.Text], [BalanceResult], []),
    'getCanisterStatus' : IDL.Func([IDL.Text], [StatusResult], []),
    'getMonitoredCanisters' : IDL.Func([], [IDL.Vec(CanisterStatusInfo)], []),
    'setAlertEnabled' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setThreshold' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };