/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export type CanisterId = Principal;
export interface CanisterStatusInfo {
    status: string;
    controllers: Array<Principal>;
    balance: bigint;
    threshold: bigint;
    alertEnabled: boolean;
    lastChecked: Timestamp;
    belowThreshold: boolean;
    canisterId: CanisterId;
}
export type StatusResult = {
    __kind__: "ok";
    ok: CanisterStatusInfo;
} | {
    __kind__: "err";
    err: string;
};
export interface BurnRateInfo {
    cyclesPerDay: number;
    projectedDepletionDate: Timestamp;
    snapshotCount: bigint;
    daysRemaining: number;
}
export type BalanceResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface BalanceSnapshot {
    balance: bigint;
    timestamp: Timestamp;
    canisterId: CanisterId;
}
export interface backendInterface {
    connectCanister(canisterId: string): Promise<void>;
    disconnectCanister(canisterId: string): Promise<void>;
    getBackendCanisterId(): Promise<string>;
    getBalanceHistory(canisterId: string): Promise<Array<BalanceSnapshot>>;
    getBurnRate(canisterId: string): Promise<BurnRateInfo>;
    getCanisterCycleBalance(canisterId: string): Promise<BalanceResult>;
    getCanisterStatus(canisterId: string): Promise<StatusResult>;
    getMonitoredCanisters(): Promise<Array<CanisterStatusInfo>>;
    setAlertEnabled(canisterId: string, enabled: boolean): Promise<void>;
    setThreshold(canisterId: string, thresholdCycles: bigint): Promise<void>;
}
import type { BalanceResult as _BalanceResult, CanisterStatusInfo as _CanisterStatusInfo, StatusResult as _StatusResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async connectCanister(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectCanister(arg0);
            return result;
        }
    }
    async disconnectCanister(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectCanister(arg0);
            return result;
        }
    }
    async getBackendCanisterId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackendCanisterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackendCanisterId();
            return result;
        }
    }
    async getBalanceHistory(arg0: string): Promise<Array<BalanceSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalanceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalanceHistory(arg0);
            return result;
        }
    }
    async getBurnRate(arg0: string): Promise<BurnRateInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getBurnRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBurnRate(arg0);
            return result;
        }
    }
    async getCanisterCycleBalance(arg0: string): Promise<BalanceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterCycleBalance(arg0);
                return from_candid_BalanceResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterCycleBalance(arg0);
            return from_candid_BalanceResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterStatus(arg0: string): Promise<StatusResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterStatus(arg0);
                return from_candid_StatusResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterStatus(arg0);
            return from_candid_StatusResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonitoredCanisters(): Promise<Array<CanisterStatusInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonitoredCanisters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonitoredCanisters();
            return result;
        }
    }
    async setAlertEnabled(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAlertEnabled(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAlertEnabled(arg0, arg1);
            return result;
        }
    }
    async setThreshold(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setThreshold(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setThreshold(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BalanceResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BalanceResult): BalanceResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_StatusResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusResult): StatusResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CanisterStatusInfo;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CanisterStatusInfo;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
