/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type CanisterId = Principal;
export interface CanisterResources {
    memory: MemoryBreakdown;
    burnRateCyclesPerDay: bigint;
    cycleBalance: Cycles;
    settings: CanisterSettings;
    runwayDays: bigint;
}
export interface CanisterSettings {
    freezingThreshold: bigint;
    memoryAllocation: bigint;
    computeAllocation: bigint;
}
export type CanisterStatus = {
    __kind__: "stopped";
    stopped: null;
} | {
    __kind__: "stopping";
    stopping: null;
} | {
    __kind__: "unknown";
    unknown: string;
} | {
    __kind__: "running";
    running: null;
};
export interface CanisterStatusInfo {
    status: CanisterStatus;
    controllers: Array<string>;
    resources: CanisterResources;
    canisterId: CanisterId;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Cycles = bigint;
export interface IcpToCyclesRate {
    icpPerXdr: bigint;
    updatedAt: Timestamp;
}
export interface ManagedCanister {
    addedAt: Timestamp;
    canisterId: CanisterId;
}
export interface MemoryBreakdown {
    stableBytes: bigint;
    heapBytes: bigint;
    wasmBytes: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface backendInterface {
    addCanister(canisterId: string): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getActiveCanister(): Promise<CanisterId | null>;
    getApiDoc(): Promise<string>;
    getBackendCanisterId(): Promise<string>;
    getCanisterCycleBalance(canisterId: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCanisterResources(canisterId: string): Promise<{
        __kind__: "ok";
        ok: CanisterResources;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCanisterStatus(canisterId: string): Promise<{
        __kind__: "ok";
        ok: CanisterStatusInfo;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getIcpToCyclesRate(): Promise<IcpToCyclesRate>;
    listManagedCanisters(): Promise<Array<ManagedCanister>>;
    refreshIcpToCyclesRate(): Promise<IcpToCyclesRate>;
    removeCanister(canisterId: string): Promise<void>;
    schema(): Promise<string>;
    setActiveCanister(canisterId: string): Promise<void>;
}
import type { CanisterId as _CanisterId, CanisterResources as _CanisterResources, CanisterStatus as _CanisterStatus, CanisterStatusInfo as _CanisterStatusInfo, Cell as _Cell, Result as _Result, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCanister(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCanister(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveCanister(): Promise<CanisterId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCanister();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCanister();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getBackendCanisterId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackendCanisterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackendCanisterId();
            return result;
        }
    }
    async getCanisterCycleBalance(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterCycleBalance(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterCycleBalance(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterResources(arg0: string): Promise<{
        __kind__: "ok";
        ok: CanisterResources;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterResources(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterResources(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterStatus(arg0: string): Promise<{
        __kind__: "ok";
        ok: CanisterStatusInfo;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterStatus(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterStatus(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIcpToCyclesRate(): Promise<IcpToCyclesRate> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcpToCyclesRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcpToCyclesRate();
            return result;
        }
    }
    async listManagedCanisters(): Promise<Array<ManagedCanister>> {
        if (this.processError) {
            try {
                const result = await this.actor.listManagedCanisters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listManagedCanisters();
            return result;
        }
    }
    async refreshIcpToCyclesRate(): Promise<IcpToCyclesRate> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshIcpToCyclesRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshIcpToCyclesRate();
            return result;
        }
    }
    async removeCanister(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCanister(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setActiveCanister(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveCanister(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveCanister(arg0);
            return result;
        }
    }
}
function from_candid_CanisterStatusInfo_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CanisterStatusInfo): CanisterStatusInfo {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_CanisterStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CanisterStatus): CanisterStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CanisterId]): CanisterId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CanisterStatus;
    controllers: Array<string>;
    resources: _CanisterResources;
    canisterId: _CanisterId;
}): {
    status: CanisterStatus;
    controllers: Array<string>;
    resources: CanisterResources;
    canisterId: CanisterId;
} {
    return {
        status: from_candid_CanisterStatus_n15(_uploadFile, _downloadFile, value.status),
        controllers: value.controllers,
        resources: value.resources,
        canisterId: value.canisterId
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n3(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n7(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CanisterResources;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CanisterResources;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CanisterStatusInfo;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CanisterStatusInfo;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CanisterStatusInfo_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stopped: null;
} | {
    stopping: null;
} | {
    unknown: string;
} | {
    running: null;
}): {
    __kind__: "stopped";
    stopped: null;
} | {
    __kind__: "stopping";
    stopping: null;
} | {
    __kind__: "unknown";
    unknown: string;
} | {
    __kind__: "running";
    running: null;
} {
    return "stopped" in value ? {
        __kind__: "stopped",
        stopped: value.stopped
    } : "stopping" in value ? {
        __kind__: "stopping",
        stopping: value.stopping
    } : "unknown" in value ? {
        __kind__: "unknown",
        unknown: value.unknown
    } : "running" in value ? {
        __kind__: "running",
        running: value.running
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
